# Generated by Django 4.1 on 2022-09-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.DecimalField(decimal_places=0, max_digits=2)),
                ('subject', models.CharField(choices=[('Arabic', 'Arabic'), ('English', 'English'), ('Maths', 'Maths'), ('Social Studies', 'Social Studies'), ('Sciences', 'Sciences'), ('Art Education', 'Art Education'), ('Religious Education', 'Religious Education'), ('Music Education', 'Music Education'), ('Information Technology', 'Information Technology')], default='Arabic', max_length=50)),
                ('describtion', models.TextField(blank=True, default='', null=True)),
                ('image', models.ImageField(upload_to='photo%y%m%d')),
                ('salary', models.DecimalField(decimal_places=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
