# Generated by Django 4.1 on 2022-09-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(choices=[('Arabic', 'Arabic'), ('English', 'English'), ('Maths', 'Maths'), ('Social Studies', 'Social Studies'), ('Sciences', 'Sciences'), ('Art Education', 'Art Education'), ('Religious Education', 'Religious Education'), ('Music Education', 'Music Education'), ('Information Technology', 'Information Technology')], default='Arabic', max_length=50),
        ),
    ]
