# Generated by Django 4.1 on 2022-09-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('trouser', 'Trouser'), ('T-shirt', 'T Shirt')], default='T-shirt', max_length=10)),
                ('price', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
    ]
