# Generated by Django 4.1 on 2022-09-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0003_alter_clothes_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='type',
            field=models.CharField(choices=[('trouser', 'Trouser'), ('T-shirt', 'T Shirt')], default='T-shirt', max_length=10),
        ),
    ]
