# Generated by Django 4.1 on 2022-09-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='class_name',
            new_name='Class',
        ),
        migrations.AddField(
            model_name='student',
            name='school_year',
            field=models.CharField(choices=[('First grade', 'First Grade'), ('Second grade', 'Second Grade'), ('third grade', 'Third Grade'), ('fourth grade', 'Fourth Grade'), ('fifth grade', 'Fifth Grade'), ('Sixth grade', 'Sixth Grade')], default='First grade', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=7),
        ),
    ]
